### ISSUE TITLE
Upgrade to create-react-app 2.0

### ISSUE THREAD

**Issue by njam3** [Jam3/nyg-jam3#189]
Will require a bit of an overhaul, but the benefits should be worth it.

**Comment by DonghyukJacobJang** [comment]
I have been looking into this, and working in progress with CRA 2.1.1. PR will be created soon

**Comment by DonghyukJacobJang** [comment]
1. Forked CRA into Jam3 repo https://github.com/Jam3/create-react-app
2. Published custom CRA https://www.npmjs.com/package/jam3-react-scripts

**Comment by DonghyukJacobJang** [comment]
the branch that I am working on is `feature/templates-2.1.1`
