### ISSUE TITLE
Fork this project using Preact

### ISSUE THREAD

**Issue by iranreyes** [Jam3/nyg-jam3#35]
Like everyone knows Preact is just ~3kb compared with the ~45kb of React. For small projects that don't require all the React architecture, we have Preact as a solution. There are more alternatives.

https://github.com/developit/preact/wiki/Differences-to-React

Note: We can think too about adding a prompt to this generator to switch to Preact, depending on how complex may be, will be better to keep it simple and just fork it and create another generator

**Comment by neo** [comment]
we voted to not implement democratically.
