### ISSUE TITLE
Exclude completely the polyfills

### ISSUE THREAD

**Issue by iranreyes** [Jam3/nyg-jam3#9]
Currently, we have control only over a few polyfills, the idea is to extract all the polyfills of the app and load them just if the browser needs them.

**Comment by namniak** [comment]
I had this code in one of my branches before
@iranreyes @neo 
https://github.com/Jam3/nyg-jam3/compare/polyfill?expand=1
it's using polyfill.io to load required polyfills.

keep in mind that if the app is gonna break in the browser without polyfills, the framework would need to be initialized on polyfills load complete - meaning you get a "white screen" while polyfills loading.
